apiVersion: apps/v1
kind: Deployment
metadata: 
  name: web
spec:
  replicas: 6
  selector: 
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: tiagosarri/conversao-temperatura:v1
          ports:
          - containerPort: 8080
          env:
          - name: DB_DATABASE
            value: "kubenews"
          - name: DB_USERNAME
            value: "kubenews"
          - name: DB_PASSWORD
            value: "P@ssword159357"
          - name: DB_HOST
            value: "postgre"

---

apiVersion: v1
kind: Service
metadata: 
  name: web
spec:
  selector:
    app: web
  ports: 
    - port: 80
      targetPort: 8080
      nodePort: 30000
  type: NodePort